// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod dispatch {
    pub mod courier {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct ConversationMessage {
                pub role: _rt::String,
                pub content: _rt::String,
            }
            impl ::core::fmt::Debug for ConversationMessage {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ConversationMessage")
                        .field("role", &self.role)
                        .field("content", &self.content)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct LocalTool {
                pub alias: _rt::String,
                pub description: Option<_rt::String>,
                pub input_schema_json: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for LocalTool {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LocalTool")
                        .field("alias", &self.alias)
                        .field("description", &self.description)
                        .field("input-schema-json", &self.input_schema_json)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum ModelToolKind {
                Custom,
                Function,
            }
            impl ::core::fmt::Debug for ModelToolKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ModelToolKind::Custom => {
                            f.debug_tuple("ModelToolKind::Custom").finish()
                        }
                        ModelToolKind::Function => {
                            f.debug_tuple("ModelToolKind::Function").finish()
                        }
                    }
                }
            }
            impl ModelToolKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> ModelToolKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => ModelToolKind::Custom,
                        1 => ModelToolKind::Function,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct ModelTool {
                pub name: _rt::String,
                pub description: _rt::String,
                pub kind: ModelToolKind,
                pub input_schema_json: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for ModelTool {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ModelTool")
                        .field("name", &self.name)
                        .field("description", &self.description)
                        .field("kind", &self.kind)
                        .field("input-schema-json", &self.input_schema_json)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ModelToolCall {
                pub call_id: _rt::String,
                pub name: _rt::String,
                pub input: _rt::String,
                pub kind: ModelToolKind,
            }
            impl ::core::fmt::Debug for ModelToolCall {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ModelToolCall")
                        .field("call-id", &self.call_id)
                        .field("name", &self.name)
                        .field("input", &self.input)
                        .field("kind", &self.kind)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ModelResponse {
                pub backend: _rt::String,
                pub text: Option<_rt::String>,
                pub response_id: Option<_rt::String>,
                pub tool_calls: _rt::Vec<ModelToolCall>,
            }
            impl ::core::fmt::Debug for ModelResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ModelResponse")
                        .field("backend", &self.backend)
                        .field("text", &self.text)
                        .field("response-id", &self.response_id)
                        .field("tool-calls", &self.tool_calls)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ModelToolOutput {
                pub call_id: _rt::String,
                pub output: _rt::String,
                pub kind: ModelToolKind,
            }
            impl ::core::fmt::Debug for ModelToolOutput {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ModelToolOutput")
                        .field("call-id", &self.call_id)
                        .field("output", &self.output)
                        .field("kind", &self.kind)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ModelRequest {
                pub model: Option<_rt::String>,
                pub instructions: _rt::String,
                pub messages: _rt::Vec<ConversationMessage>,
                pub tools: _rt::Vec<ModelTool>,
                pub tool_outputs: _rt::Vec<ModelToolOutput>,
                pub previous_response_id: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for ModelRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ModelRequest")
                        .field("model", &self.model)
                        .field("instructions", &self.instructions)
                        .field("messages", &self.messages)
                        .field("tools", &self.tools)
                        .field("tool-outputs", &self.tool_outputs)
                        .field("previous-response-id", &self.previous_response_id)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ToolInvocation {
                pub name: _rt::String,
                pub input: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for ToolInvocation {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ToolInvocation")
                        .field("name", &self.name)
                        .field("input", &self.input)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ToolResult {
                pub tool: _rt::String,
                pub command: _rt::String,
                pub args: _rt::Vec<_rt::String>,
                pub exit_code: i32,
                pub stdout: _rt::String,
                pub stderr: _rt::String,
            }
            impl ::core::fmt::Debug for ToolResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ToolResult")
                        .field("tool", &self.tool)
                        .field("command", &self.command)
                        .field("args", &self.args)
                        .field("exit-code", &self.exit_code)
                        .field("stdout", &self.stdout)
                        .field("stderr", &self.stderr)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn model_complete(
                request: &ModelRequest,
            ) -> Result<ModelResponse, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 11 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 11
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ModelRequest {
                        model: model0,
                        instructions: instructions0,
                        messages: messages0,
                        tools: tools0,
                        tool_outputs: tool_outputs0,
                        previous_response_id: previous_response_id0,
                    } = request;
                    let (result2_0, result2_1, result2_2) = match model0 {
                        Some(e) => {
                            let vec1 = e;
                            let ptr1 = vec1.as_ptr().cast::<u8>();
                            let len1 = vec1.len();
                            (1i32, ptr1.cast_mut(), len1)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let vec3 = instructions0;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    let vec7 = messages0;
                    let len7 = vec7.len();
                    let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec7.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result7 = if layout7.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout7);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec7.into_iter().enumerate() {
                        let base = result7
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let ConversationMessage { role: role4, content: content4 } = e;
                            let vec5 = role4;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = content4;
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    }
                    let vec12 = tools0;
                    let len12 = vec12.len();
                    let layout12 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec12.len() * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result12 = if layout12.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout12).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout12);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec12.into_iter().enumerate() {
                        let base = result12
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        {
                            let ModelTool {
                                name: name8,
                                description: description8,
                                kind: kind8,
                                input_schema_json: input_schema_json8,
                            } = e;
                            let vec9 = name8;
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *base.add(0).cast::<*mut u8>() = ptr9.cast_mut();
                            let vec10 = description8;
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (kind8.clone() as i32) as u8;
                            match input_schema_json8 {
                                Some(e) => {
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec11 = e;
                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                    let len11 = vec11.len();
                                    *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len11;
                                    *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr11.cast_mut();
                                }
                                None => {
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                    }
                    let vec16 = tool_outputs0;
                    let len16 = vec16.len();
                    let layout16 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec16.len() * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result16 = if layout16.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout16).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout16);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec16.into_iter().enumerate() {
                        let base = result16
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        {
                            let ModelToolOutput {
                                call_id: call_id13,
                                output: output13,
                                kind: kind13,
                            } = e;
                            let vec14 = call_id13;
                            let ptr14 = vec14.as_ptr().cast::<u8>();
                            let len14 = vec14.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len14;
                            *base.add(0).cast::<*mut u8>() = ptr14.cast_mut();
                            let vec15 = output13;
                            let ptr15 = vec15.as_ptr().cast::<u8>();
                            let len15 = vec15.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len15;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr15.cast_mut();
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (kind13.clone() as i32) as u8;
                        }
                    }
                    let (result18_0, result18_1, result18_2) = match previous_response_id0 {
                        Some(e) => {
                            let vec17 = e;
                            let ptr17 = vec17.as_ptr().cast::<u8>();
                            let len17 = vec17.len();
                            (1i32, ptr17.cast_mut(), len17)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let ptr19 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "dispatch:courier/host@0.0.1")]
                    unsafe extern "C" {
                        #[link_name = "model-complete"]
                        fn wit_import20(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import20(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import20(
                            result2_0,
                            result2_1,
                            result2_2,
                            ptr3.cast_mut(),
                            len3,
                            result7,
                            len7,
                            result12,
                            len12,
                            result16,
                            len16,
                            result18_0,
                            result18_1,
                            result18_2,
                            ptr19,
                        )
                    };
                    let l21 = i32::from(*ptr19.add(0).cast::<u8>());
                    let result49 = match l21 {
                        0 => {
                            let e = {
                                let l22 = *ptr19
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l23 = *ptr19
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len24 = l23;
                                let bytes24 = _rt::Vec::from_raw_parts(
                                    l22.cast(),
                                    len24,
                                    len24,
                                );
                                let l25 = i32::from(
                                    *ptr19
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>(),
                                );
                                let l29 = i32::from(
                                    *ptr19
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>(),
                                );
                                let l33 = *ptr19
                                    .add(9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l34 = *ptr19
                                    .add(10 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base45 = l33;
                                let len45 = l34;
                                let mut result45 = _rt::Vec::with_capacity(len45);
                                for i in 0..len45 {
                                    let base = base45
                                        .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                                    let e45 = {
                                        let l35 = *base.add(0).cast::<*mut u8>();
                                        let l36 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len37 = l36;
                                        let bytes37 = _rt::Vec::from_raw_parts(
                                            l35.cast(),
                                            len37,
                                            len37,
                                        );
                                        let l38 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l39 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len40 = l39;
                                        let bytes40 = _rt::Vec::from_raw_parts(
                                            l38.cast(),
                                            len40,
                                            len40,
                                        );
                                        let l41 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l42 = *base
                                            .add(5 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len43 = l42;
                                        let bytes43 = _rt::Vec::from_raw_parts(
                                            l41.cast(),
                                            len43,
                                            len43,
                                        );
                                        let l44 = i32::from(
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        ModelToolCall {
                                            call_id: _rt::string_lift(bytes37),
                                            name: _rt::string_lift(bytes40),
                                            input: _rt::string_lift(bytes43),
                                            kind: ModelToolKind::_lift(l44 as u8),
                                        }
                                    };
                                    result45.push(e45);
                                }
                                _rt::cabi_dealloc(
                                    base45,
                                    len45 * (7 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                ModelResponse {
                                    backend: _rt::string_lift(bytes24),
                                    text: match l25 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l26 = *ptr19
                                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<*mut u8>();
                                                let l27 = *ptr19
                                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<usize>();
                                                let len28 = l27;
                                                let bytes28 = _rt::Vec::from_raw_parts(
                                                    l26.cast(),
                                                    len28,
                                                    len28,
                                                );
                                                _rt::string_lift(bytes28)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    },
                                    response_id: match l29 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l30 = *ptr19
                                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<*mut u8>();
                                                let l31 = *ptr19
                                                    .add(8 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<usize>();
                                                let len32 = l31;
                                                let bytes32 = _rt::Vec::from_raw_parts(
                                                    l30.cast(),
                                                    len32,
                                                    len32,
                                                );
                                                _rt::string_lift(bytes32)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    },
                                    tool_calls: result45,
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l46 = *ptr19
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l47 = *ptr19
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len48 = l47;
                                let bytes48 = _rt::Vec::from_raw_parts(
                                    l46.cast(),
                                    len48,
                                    len48,
                                );
                                _rt::string_lift(bytes48)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout7.size() != 0 {
                        _rt::alloc::dealloc(result7.cast(), layout7);
                    }
                    if layout12.size() != 0 {
                        _rt::alloc::dealloc(result12.cast(), layout12);
                    }
                    if layout16.size() != 0 {
                        _rt::alloc::dealloc(result16.cast(), layout16);
                    }
                    result49
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn invoke_tool(
                invocation: &ToolInvocation,
            ) -> Result<ToolResult, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 12 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 12
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ToolInvocation { name: name0, input: input0 } = invocation;
                    let vec1 = name0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let (result3_0, result3_1, result3_2) = match input0 {
                        Some(e) => {
                            let vec2 = e;
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            (1i32, ptr2.cast_mut(), len2)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let ptr4 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "dispatch:courier/host@0.0.1")]
                    unsafe extern "C" {
                        #[link_name = "invoke-tool"]
                        fn wit_import5(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import5(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import5(
                            ptr1.cast_mut(),
                            len1,
                            result3_0,
                            result3_1,
                            result3_2,
                            ptr4,
                        )
                    };
                    let l6 = i32::from(*ptr4.add(0).cast::<u8>());
                    let result29 = match l6 {
                        0 => {
                            let e = {
                                let l7 = *ptr4
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l8 = *ptr4
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len9 = l8;
                                let bytes9 = _rt::Vec::from_raw_parts(
                                    l7.cast(),
                                    len9,
                                    len9,
                                );
                                let l10 = *ptr4
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *ptr4
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len12 = l11;
                                let bytes12 = _rt::Vec::from_raw_parts(
                                    l10.cast(),
                                    len12,
                                    len12,
                                );
                                let l13 = *ptr4
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l14 = *ptr4
                                    .add(6 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base18 = l13;
                                let len18 = l14;
                                let mut result18 = _rt::Vec::with_capacity(len18);
                                for i in 0..len18 {
                                    let base = base18
                                        .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                    let e18 = {
                                        let l15 = *base.add(0).cast::<*mut u8>();
                                        let l16 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len17 = l16;
                                        let bytes17 = _rt::Vec::from_raw_parts(
                                            l15.cast(),
                                            len17,
                                            len17,
                                        );
                                        _rt::string_lift(bytes17)
                                    };
                                    result18.push(e18);
                                }
                                _rt::cabi_dealloc(
                                    base18,
                                    len18 * (2 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                let l19 = *ptr4
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<i32>();
                                let l20 = *ptr4
                                    .add(8 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l21 = *ptr4
                                    .add(9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len22 = l21;
                                let bytes22 = _rt::Vec::from_raw_parts(
                                    l20.cast(),
                                    len22,
                                    len22,
                                );
                                let l23 = *ptr4
                                    .add(10 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l24 = *ptr4
                                    .add(11 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len25 = l24;
                                let bytes25 = _rt::Vec::from_raw_parts(
                                    l23.cast(),
                                    len25,
                                    len25,
                                );
                                ToolResult {
                                    tool: _rt::string_lift(bytes9),
                                    command: _rt::string_lift(bytes12),
                                    args: result18,
                                    exit_code: l19,
                                    stdout: _rt::string_lift(bytes22),
                                    stderr: _rt::string_lift(bytes25),
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l26 = *ptr4
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l27 = *ptr4
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len28 = l27;
                                let bytes28 = _rt::Vec::from_raw_parts(
                                    l26.cast(),
                                    len28,
                                    len28,
                                );
                                _rt::string_lift(bytes28)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result29
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod dispatch {
        pub mod courier {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod guest {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ConversationMessage = super::super::super::super::dispatch::courier::host::ConversationMessage;
                pub type LocalTool = super::super::super::super::dispatch::courier::host::LocalTool;
                #[derive(Clone)]
                pub struct ParcelContext {
                    pub parcel_digest: _rt::String,
                    pub entrypoint: Option<_rt::String>,
                    pub prompt: _rt::String,
                    pub local_tools: _rt::Vec<LocalTool>,
                    pub primary_model: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ParcelContext {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ParcelContext")
                            .field("parcel-digest", &self.parcel_digest)
                            .field("entrypoint", &self.entrypoint)
                            .field("prompt", &self.prompt)
                            .field("local-tools", &self.local_tools)
                            .field("primary-model", &self.primary_model)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct GuestSession {
                    pub turn_count: u64,
                    pub history: _rt::Vec<ConversationMessage>,
                    pub backend_state: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for GuestSession {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("GuestSession")
                            .field("turn-count", &self.turn_count)
                            .field("history", &self.history)
                            .field("backend-state", &self.backend_state)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub enum Operation {
                    Chat(_rt::String),
                    Job(_rt::String),
                    Heartbeat(Option<_rt::String>),
                }
                impl ::core::fmt::Debug for Operation {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Operation::Chat(e) => {
                                f.debug_tuple("Operation::Chat").field(e).finish()
                            }
                            Operation::Job(e) => {
                                f.debug_tuple("Operation::Job").field(e).finish()
                            }
                            Operation::Heartbeat(e) => {
                                f.debug_tuple("Operation::Heartbeat").field(e).finish()
                            }
                        }
                    }
                }
                #[derive(Clone)]
                pub struct BackendFallback {
                    pub backend: _rt::String,
                    pub error: _rt::String,
                }
                impl ::core::fmt::Debug for BackendFallback {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("BackendFallback")
                            .field("backend", &self.backend)
                            .field("error", &self.error)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub enum GuestEvent {
                    Message(ConversationMessage),
                    TextDelta(_rt::String),
                    BackendFallback(BackendFallback),
                }
                impl ::core::fmt::Debug for GuestEvent {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            GuestEvent::Message(e) => {
                                f.debug_tuple("GuestEvent::Message").field(e).finish()
                            }
                            GuestEvent::TextDelta(e) => {
                                f.debug_tuple("GuestEvent::TextDelta").field(e).finish()
                            }
                            GuestEvent::BackendFallback(e) => {
                                f.debug_tuple("GuestEvent::BackendFallback")
                                    .field(e)
                                    .finish()
                            }
                        }
                    }
                }
                #[derive(Clone)]
                pub struct TurnResult {
                    pub backend_state: Option<_rt::String>,
                    pub events: _rt::Vec<GuestEvent>,
                }
                impl ::core::fmt::Debug for TurnResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("TurnResult")
                            .field("backend-state", &self.backend_state)
                            .field("events", &self.events)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_open_session_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: *mut u8,
                    arg8: usize,
                    arg9: i32,
                    arg10: *mut u8,
                    arg11: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    let base14 = arg7;
                    let len14 = arg8;
                    let mut result14 = _rt::Vec::with_capacity(len14);
                    for i in 0..len14 {
                        let base = base14
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        let e14 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l10 = i32::from(
                                *base
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::dispatch::courier::host::LocalTool {
                                alias: _rt::string_lift(bytes5),
                                description: match l6 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l7 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l8 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len9 = l8;
                                            let bytes9 = _rt::Vec::from_raw_parts(
                                                l7.cast(),
                                                len9,
                                                len9,
                                            );
                                            _rt::string_lift(bytes9)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                input_schema_json: match l10 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l11 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l12 = *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len13 = l12;
                                            let bytes13 = _rt::Vec::from_raw_parts(
                                                l11.cast(),
                                                len13,
                                                len13,
                                            );
                                            _rt::string_lift(bytes13)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result14.push(e14);
                    }
                    _rt::cabi_dealloc(
                        base14,
                        len14 * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result16 = T::open_session(ParcelContext {
                        parcel_digest: _rt::string_lift(bytes0),
                        entrypoint: match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg4;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg3.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        prompt: _rt::string_lift(bytes2),
                        local_tools: result14,
                        primary_model: match arg9 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len15 = arg11;
                                    let bytes15 = _rt::Vec::from_raw_parts(
                                        arg10.cast(),
                                        len15,
                                        len15,
                                    );
                                    _rt::string_lift(bytes15)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr17 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result16 {
                        Ok(e) => {
                            *ptr17.add(0).cast::<u8>() = (0i32) as u8;
                            match e {
                                Some(e) => {
                                    *ptr17
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec18 = (e.into_bytes()).into_boxed_slice();
                                    let ptr18 = vec18.as_ptr().cast::<u8>();
                                    let len18 = vec18.len();
                                    ::core::mem::forget(vec18);
                                    *ptr17
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len18;
                                    *ptr17
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr18.cast_mut();
                                }
                                None => {
                                    *ptr17
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr17.add(0).cast::<u8>() = (1i32) as u8;
                            let vec19 = (e.into_bytes()).into_boxed_slice();
                            let ptr19 = vec19.as_ptr().cast::<u8>();
                            let len19 = vec19.len();
                            ::core::mem::forget(vec19);
                            *ptr17
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len19;
                            *ptr17
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr19.cast_mut();
                        }
                    };
                    ptr17
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_open_session<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handle_operation_cabi<T: Guest>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len2 = l1;
                    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                    let l3 = i32::from(
                        *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l7 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l8 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len9 = l8;
                    let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                    let l10 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l11 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base23 = l10;
                    let len23 = l11;
                    let mut result23 = _rt::Vec::with_capacity(len23);
                    for i in 0..len23 {
                        let base = base23
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        let e23 = {
                            let l12 = *base.add(0).cast::<*mut u8>();
                            let l13 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            let l15 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l19 = i32::from(
                                *base
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::dispatch::courier::host::LocalTool {
                                alias: _rt::string_lift(bytes14),
                                description: match l15 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l16 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l17 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len18 = l17;
                                            let bytes18 = _rt::Vec::from_raw_parts(
                                                l16.cast(),
                                                len18,
                                                len18,
                                            );
                                            _rt::string_lift(bytes18)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                input_schema_json: match l19 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l20 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l21 = *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len22 = l21;
                                            let bytes22 = _rt::Vec::from_raw_parts(
                                                l20.cast(),
                                                len22,
                                                len22,
                                            );
                                            _rt::string_lift(bytes22)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result23.push(e23);
                    }
                    _rt::cabi_dealloc(
                        base23,
                        len23 * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l24 = i32::from(
                        *arg0.add(9 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l28 = *arg0
                        .add(12 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let l29 = *arg0
                        .add(8 + 12 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l30 = *arg0
                        .add(8 + 13 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base37 = l29;
                    let len37 = l30;
                    let mut result37 = _rt::Vec::with_capacity(len37);
                    for i in 0..len37 {
                        let base = base37
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e37 = {
                            let l31 = *base.add(0).cast::<*mut u8>();
                            let l32 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len33 = l32;
                            let bytes33 = _rt::Vec::from_raw_parts(
                                l31.cast(),
                                len33,
                                len33,
                            );
                            let l34 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l35 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len36 = l35;
                            let bytes36 = _rt::Vec::from_raw_parts(
                                l34.cast(),
                                len36,
                                len36,
                            );
                            super::super::super::super::dispatch::courier::host::ConversationMessage {
                                role: _rt::string_lift(bytes33),
                                content: _rt::string_lift(bytes36),
                            }
                        };
                        result37.push(e37);
                    }
                    _rt::cabi_dealloc(
                        base37,
                        len37 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l38 = i32::from(
                        *arg0
                            .add(8 + 14 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l42 = i32::from(
                        *arg0
                            .add(16 + 16 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let v53 = match l42 {
                        0 => {
                            let e53 = {
                                let l43 = *arg0
                                    .add(16 + 17 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l44 = *arg0
                                    .add(16 + 18 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len45 = l44;
                                let bytes45 = _rt::Vec::from_raw_parts(
                                    l43.cast(),
                                    len45,
                                    len45,
                                );
                                _rt::string_lift(bytes45)
                            };
                            Operation::Chat(e53)
                        }
                        1 => {
                            let e53 = {
                                let l46 = *arg0
                                    .add(16 + 17 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l47 = *arg0
                                    .add(16 + 18 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len48 = l47;
                                let bytes48 = _rt::Vec::from_raw_parts(
                                    l46.cast(),
                                    len48,
                                    len48,
                                );
                                _rt::string_lift(bytes48)
                            };
                            Operation::Job(e53)
                        }
                        n => {
                            debug_assert_eq!(n, 2, "invalid enum discriminant");
                            let e53 = {
                                let l49 = i32::from(
                                    *arg0
                                        .add(16 + 17 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>(),
                                );
                                match l49 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l50 = *arg0
                                                .add(16 + 18 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l51 = *arg0
                                                .add(16 + 19 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len52 = l51;
                                            let bytes52 = _rt::Vec::from_raw_parts(
                                                l50.cast(),
                                                len52,
                                                len52,
                                            );
                                            _rt::string_lift(bytes52)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                }
                            };
                            Operation::Heartbeat(e53)
                        }
                    };
                    let result54 = T::handle_operation(
                        ParcelContext {
                            parcel_digest: _rt::string_lift(bytes2),
                            entrypoint: match l3 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l4 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len6 = l5;
                                        let bytes6 = _rt::Vec::from_raw_parts(
                                            l4.cast(),
                                            len6,
                                            len6,
                                        );
                                        _rt::string_lift(bytes6)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            prompt: _rt::string_lift(bytes9),
                            local_tools: result23,
                            primary_model: match l24 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l25 = *arg0
                                            .add(10 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l26 = *arg0
                                            .add(11 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len27 = l26;
                                        let bytes27 = _rt::Vec::from_raw_parts(
                                            l25.cast(),
                                            len27,
                                            len27,
                                        );
                                        _rt::string_lift(bytes27)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                        GuestSession {
                            turn_count: l28 as u64,
                            history: result37,
                            backend_state: match l38 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l39 = *arg0
                                            .add(8 + 15 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l40 = *arg0
                                            .add(8 + 16 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len41 = l40;
                                        let bytes41 = _rt::Vec::from_raw_parts(
                                            l39.cast(),
                                            len41,
                                            len41,
                                        );
                                        _rt::string_lift(bytes41)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                        v53,
                    );
                    _rt::cabi_dealloc(
                        arg0,
                        16 + 20 * ::core::mem::size_of::<*const u8>(),
                        8,
                    );
                    let ptr55 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result54 {
                        Ok(e) => {
                            *ptr55.add(0).cast::<u8>() = (0i32) as u8;
                            let TurnResult {
                                backend_state: backend_state56,
                                events: events56,
                            } = e;
                            match backend_state56 {
                                Some(e) => {
                                    *ptr55
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec57 = (e.into_bytes()).into_boxed_slice();
                                    let ptr57 = vec57.as_ptr().cast::<u8>();
                                    let len57 = vec57.len();
                                    ::core::mem::forget(vec57);
                                    *ptr55
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len57;
                                    *ptr55
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr57.cast_mut();
                                }
                                None => {
                                    *ptr55
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec65 = events56;
                            let len65 = vec65.len();
                            let layout65 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec65.len() * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result65 = if layout65.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout65).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout65);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec65.into_iter().enumerate() {
                                let base = result65
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    match e {
                                        GuestEvent::Message(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let super::super::super::super::dispatch::courier::host::ConversationMessage {
                                                role: role58,
                                                content: content58,
                                            } = e;
                                            let vec59 = (role58.into_bytes()).into_boxed_slice();
                                            let ptr59 = vec59.as_ptr().cast::<u8>();
                                            let len59 = vec59.len();
                                            ::core::mem::forget(vec59);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len59;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr59.cast_mut();
                                            let vec60 = (content58.into_bytes()).into_boxed_slice();
                                            let ptr60 = vec60.as_ptr().cast::<u8>();
                                            let len60 = vec60.len();
                                            ::core::mem::forget(vec60);
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len60;
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr60.cast_mut();
                                        }
                                        GuestEvent::TextDelta(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let vec61 = (e.into_bytes()).into_boxed_slice();
                                            let ptr61 = vec61.as_ptr().cast::<u8>();
                                            let len61 = vec61.len();
                                            ::core::mem::forget(vec61);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len61;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr61.cast_mut();
                                        }
                                        GuestEvent::BackendFallback(e) => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                            let BackendFallback {
                                                backend: backend62,
                                                error: error62,
                                            } = e;
                                            let vec63 = (backend62.into_bytes()).into_boxed_slice();
                                            let ptr63 = vec63.as_ptr().cast::<u8>();
                                            let len63 = vec63.len();
                                            ::core::mem::forget(vec63);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len63;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr63.cast_mut();
                                            let vec64 = (error62.into_bytes()).into_boxed_slice();
                                            let ptr64 = vec64.as_ptr().cast::<u8>();
                                            let len64 = vec64.len();
                                            ::core::mem::forget(vec64);
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len64;
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr64.cast_mut();
                                        }
                                    }
                                }
                            }
                            *ptr55
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len65;
                            *ptr55
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result65;
                        }
                        Err(e) => {
                            *ptr55.add(0).cast::<u8>() = (1i32) as u8;
                            let vec66 = (e.into_bytes()).into_boxed_slice();
                            let ptr66 = vec66.as_ptr().cast::<u8>();
                            let len66 = vec66.len();
                            ::core::mem::forget(vec66);
                            *ptr55
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len66;
                            *ptr55
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr66.cast_mut();
                        }
                    };
                    ptr55
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handle_operation<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base17 = l4;
                            let len17 = l5;
                            for i in 0..len17 {
                                let base = base17
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l6 = i32::from(*base.add(0).cast::<u8>());
                                    match l6 {
                                        0 => {
                                            let l7 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l8 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l7, l8, 1);
                                            let l9 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l10 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l9, l10, 1);
                                        }
                                        1 => {
                                            let l11 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l12 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l11, l12, 1);
                                        }
                                        _ => {
                                            let l13 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l14 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l13, l14, 1);
                                            let l15 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l16 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l15, l16, 1);
                                        }
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base17,
                                len17 * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l18 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l19 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l18, l19, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn open_session(
                        parcel: ParcelContext,
                    ) -> Result<Option<_rt::String>, _rt::String>;
                    fn handle_operation(
                        parcel: ParcelContext,
                        session: GuestSession,
                        operation: Operation,
                    ) -> Result<TurnResult, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_dispatch_courier_guest_0_0_1_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "dispatch:courier/guest@0.0.1#open-session")] unsafe extern "C"
                        fn export_open_session(arg0 : * mut u8, arg1 : usize, arg2 : i32,
                        arg3 : * mut u8, arg4 : usize, arg5 : * mut u8, arg6 : usize,
                        arg7 : * mut u8, arg8 : usize, arg9 : i32, arg10 : * mut u8,
                        arg11 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_open_session_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6, arg7, arg8, arg9, arg10, arg11) } } #[unsafe
                        (export_name =
                        "cabi_post_dispatch:courier/guest@0.0.1#open-session")] unsafe
                        extern "C" fn _post_return_open_session(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_open_session::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "dispatch:courier/guest@0.0.1#handle-operation")] unsafe extern
                        "C" fn export_handle_operation(arg0 : * mut u8,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_handle_operation_cabi::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "cabi_post_dispatch:courier/guest@0.0.1#handle-operation")]
                        unsafe extern "C" fn _post_return_handle_operation(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_handle_operation::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_dispatch_courier_guest_0_0_1_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 6
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_courier_guest_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::dispatch::courier::guest::__export_dispatch_courier_guest_0_0_1_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::dispatch::courier::guest);
    };
}
#[doc(inline)]
pub(crate) use __export_courier_guest_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:dispatch:courier@0.0.1:courier-guest:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1455] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xab\x0a\x01A\x02\x01\
A\x06\x01B\x20\x01r\x02\x04roles\x07contents\x04\0\x14conversation-message\x03\0\
\0\x01ks\x01r\x03\x05aliass\x0bdescription\x02\x11input-schema-json\x02\x04\0\x0a\
local-tool\x03\0\x03\x01m\x02\x06custom\x08function\x04\0\x0fmodel-tool-kind\x03\
\0\x05\x01r\x04\x04names\x0bdescriptions\x04kind\x06\x11input-schema-json\x02\x04\
\0\x0amodel-tool\x03\0\x07\x01r\x04\x07call-ids\x04names\x05inputs\x04kind\x06\x04\
\0\x0fmodel-tool-call\x03\0\x09\x01p\x0a\x01r\x04\x07backends\x04text\x02\x0bres\
ponse-id\x02\x0atool-calls\x0b\x04\0\x0emodel-response\x03\0\x0c\x01r\x03\x07cal\
l-ids\x06outputs\x04kind\x06\x04\0\x11model-tool-output\x03\0\x0e\x01p\x01\x01p\x08\
\x01p\x0f\x01r\x06\x05model\x02\x0cinstructionss\x08messages\x10\x05tools\x11\x0c\
tool-outputs\x12\x14previous-response-id\x02\x04\0\x0dmodel-request\x03\0\x13\x01\
r\x02\x04names\x05input\x02\x04\0\x0ftool-invocation\x03\0\x15\x01ps\x01r\x06\x04\
tools\x07commands\x04args\x17\x09exit-codez\x06stdouts\x06stderrs\x04\0\x0btool-\
result\x03\0\x18\x01j\x01\x0d\x01s\x01@\x01\x07request\x14\0\x1a\x04\0\x0emodel-\
complete\x01\x1b\x01j\x01\x19\x01s\x01@\x01\x0ainvocation\x16\0\x1c\x04\0\x0binv\
oke-tool\x01\x1d\x03\0\x1bdispatch:courier/host@0.0.1\x05\0\x02\x03\0\0\x14conve\
rsation-message\x02\x03\0\0\x0alocal-tool\x01B\x1a\x02\x03\x02\x01\x01\x04\0\x14\
conversation-message\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0alocal-tool\x03\0\x02\x01\
ks\x01p\x03\x01r\x05\x0dparcel-digests\x0aentrypoint\x04\x06prompts\x0blocal-too\
ls\x05\x0dprimary-model\x04\x04\0\x0eparcel-context\x03\0\x06\x01p\x01\x01r\x03\x0a\
turn-countw\x07history\x08\x0dbackend-state\x04\x04\0\x0dguest-session\x03\0\x09\
\x01q\x03\x04chat\x01s\0\x03job\x01s\0\x09heartbeat\x01\x04\0\x04\0\x09operation\
\x03\0\x0b\x01r\x02\x07backends\x05errors\x04\0\x10backend-fallback\x03\0\x0d\x01\
q\x03\x07message\x01\x01\0\x0atext-delta\x01s\0\x10backend-fallback\x01\x0e\0\x04\
\0\x0bguest-event\x03\0\x0f\x01p\x10\x01r\x02\x0dbackend-state\x04\x06events\x11\
\x04\0\x0bturn-result\x03\0\x12\x01j\x01\x04\x01s\x01@\x01\x06parcel\x07\0\x14\x04\
\0\x0copen-session\x01\x15\x01j\x01\x13\x01s\x01@\x03\x06parcel\x07\x07session\x0a\
\x09operation\x0c\0\x16\x04\0\x10handle-operation\x01\x17\x04\0\x1cdispatch:cour\
ier/guest@0.0.1\x05\x03\x04\0$dispatch:courier/courier-guest@0.0.1\x04\0\x0b\x13\
\x01\0\x0dcourier-guest\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-c\
omponent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
